apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-site
  template:
    metadata:
      labels:
        app: resume-site
    spec:
      containers:
      - name: resume-site
        image: abdallauno1/resumeapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  selector:
    app: resume-site
  ports:
  - protocol: "TCP"
    port: 4000
    targetPort: 5000
  type: LoadBalancer
